### ISSUE TITLE
API Credentials loaded through console does not match credential name in manifest

### ISSUE THREAD

**Issue by sarahxxu** [adobe/generator-aio-app#50]
### Expected Behaviour

The API credentials loaded into `.env` should match the expected value in the manifest so that the user does not have to manually update this. 

### Actual Behaviour

To take AEP API as an example, the credentials loaded into `.env` looks like this
```
AIO_$ims_Project__xxxxxx_client__id=xxxxx
AIO_$ims_Project__xxxxxx_client__secret=xxxxx
AIO_$ims_Project__xxxxxx_techacct=axxxxx
AIO_$ims_Project__xxxxxx_meta__scopes=["ent_dataservices_sdk"]
AIO_$ims_Project__xxxxxx_ims__org__id=xxxxx@AdobeOrg
```

while the manifest expects 
```
      customer-profile:
        function: actions/customer-profile/index.js
        web: 'yes'
        runtime: 'nodejs:10'
        inputs:
          LOG_LEVEL: debug
          **tenant: $CUSTOMER_PROFILE_TENANT
          apiKey: $CUSTOMER_PROFILE_API_KEY**
        annotations:
          require-adobe-auth: true
          final: true
```

#### Steps to Reproduce

1. create project in console with AEP api subscription
1. load adobe i/o cli and do `aio app init`
1. follow the generator to select the project you've created and select to create a sample action for AEP
1. wait for project to init then check `.env` and `.aio`
